### PR TITLE
Fix #33 & #32 - building site.min.js and site.min.css for release builds and Append version for included styles

### LINKED ISSUE #33: Fix building site.min.js and site.min.css for release builds

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by maraf** [comment]
Thanks a lot!

Looks good to me, but I would like to discuss one thing:

Is there any benefit in using attribute `names` on `environment` instead of `include` and `exclude`? When I generate a new ASP.NET Core site from official template, it uses `include` and `exclude`.

**Comment by nicotravassos** [comment]
Hello @maraf,

`names` accepts a single hosting environment name or a comma-separated list of hosting environment names that trigger the rendering of the enclosed content.

`include` & `exclude` attributes control rendering the enclosed content based on the included or excluded hosting environment names.

Please this (asp-net-core-environment-tag-helper)[https://www.tektutorialshub.com/asp-net-core/asp-net-core-environment-tag-helper/]

**Comment by maraf** [comment]
So, please remove the change regarding include/exclude replacement and I'm going to merge it.

**Comment by nicotravassos** [comment]
@maraf,

Sorry about all the random commits my brain is not in a right place right now. I have removed Staging and Production will add this in next pull request when I implement bootstrap layout.

**Pull request merged**
